Feature scrollup
infoshareacademy/jfdzs2-citymap pull request #13
Opened 2018-02-27 07:08 UTC by BartoszSierakowski

Dodanie ikonki, która przenosi na górę strony, zmiana kolorystyki navi

2018-02-28 14:22 UTC, maciekmp requested changes
Bardzo fajnie jednak chciałbym aby ikona była bardziej subtelna, pojawiała się od razu po zjechaniu w dół i podczas pojawiania znikania była animacja opacity.

2018-02-28 14:22 UTC, maciekmp commented on index.html
> +<script>
Wszelkie skrypty strony powinny znaleźć się w osobnym pliku.

2018-02-28 14:22 UTC, maciekmp commented on index.html
> +        $('a[href^="#"]').on('click', function(event) {
pytanie czy użyty selektor nie jest zbyt ogólny

2018-03-06 10:09 UTC, maciekmp requested changes
Bardzo dobre zmiany, jednak przycisk ma nierówne odstępy góra-dół względem strzałki w środku, proszę o pilnowanie wszystkich odstępów.

2018-04-14 17:56 UTC, maciekmp submitted a review, later dismissed

2018-04-15 17:32 UTC, maciekmpintive approved these changes

2018-04-15 17:33 UTC, maciekmp approved these changes

2018-04-18 19:44 UTC, merged