Feature cookies
infoshareacademy/jfdzs2-citymap pull request #14
Opened 2018-03-02 15:35 UTC by katarzyna-stepczynska

Proszę o sprawdzenie pod kątem pliku JS - nie wiem czy o to chodzi.

2018-03-06 10:14 UTC, maciekmp requested changes
Bardzo bardzo dobrze.
Proszę tylko aby tło było trochę mniej przeźroczyste aby łatwiej się czytało komunikat, całość musi być bardziej responsywna gdyż przy zmniejszaniu szerokości wychodzi kilka kwiatków, na tą chwilę widzę w jednym kontenerze klasę container i col co jest złą praktyką.

2018-03-12 18:45 UTC, katarzyna-stepczynska commented
Poprawiłam wg powyższych zaleceń.

2018-03-20 20:55 UTC, katarzyna-stepczynska commented
? :) czy wszystko ok, czy jest jeszcze coś, nad czym mogłabym popracowac?

2018-03-25 17:30 UTC, maciekmp requested changes
Między .container a .col zawsze powinien być div z .row

2018-03-25 17:39 UTC, katarzyna-stepczynska commented
Wstawiłam brakujące div. Mam nadzieję że wszystko git

2018-04-07 10:26 UTC, maciekmp submitted a review, later dismissed

2018-04-11 19:45 UTC, maciekmpintive approved these changes

2018-04-11 19:46 UTC, maciekmp approved these changes

2018-04-11 19:47 UTC, merged