Feature team flip
infoshareacademy/jfdzs2-citymap pull request #15
Opened 2018-03-02 19:20 UTC by JoannaDS

Team part with flipping team photos- sprint nr 2

2018-03-06 10:18 UTC, maciekmp requested changes
działa bardzo ok, jednak chciałbym aby animacja była szybsza, nazwy nowych id popraw tak aby używały standardowej konwencji w projekcie, czyli np. #flip-container zamiast #flip_container

2018-03-25 17:29 UTC, maciekmp requested changes

2018-03-25 17:29 UTC, maciekmp commented on index.html
> +    $(document).ready(function() {
w team flip pojawił się kod od przewijania do sekcji?

2018-03-25 17:29 UTC, maciekmp commented on index.html
> -
Dlaczego style.css są dwa razy w html pobierany?

2018-04-06 10:53 UTC, maciekmpintive approved these changes

2018-04-06 10:55 UTC, maciekmp approved these changes

2018-04-06 11:04 UTC, merged